[app]
name = "PageTop"
description = "An opinionated web framework to build modular Server-Side Rendering web solutions."
theme = "Bootsier"
language = "es"

[bootsier]
max_width = "1520px"

[log]
rolling = "Daily"
