[package]
name = "drust"
version = "0.0.1"
edition = "2021"

authors = [
    "Manuel Cillero <manuel@cillero.es>"
]
description = """\
    A modern web Content Management System to share your world.\
"""
homepage = "https://suitepro.cillero.es/projects/drust"
repository = "https://gitlab.com/manuelcillero/drust"
license = "Apache-2.0 or MIT"

[dependencies.pagetop]
path = "../pagetop"
features = ["mysql"]
default-features = false

[dependencies]
actix-web = "3.3.3"
pagetop-admin = { path = "../pagetop-admin" }
pagetop-user = { path = "../pagetop-user" }
pagetop-node = { path = "../pagetop-node" }
