[package]
name = "drust"
version = "0.0.2"
edition = "2021"

authors = [
    "Manuel Cillero <manuel@cillero.es>"
]
description = """\
    A modern web Content Management System to share your world.\
"""
homepage = "https://pagetop.cillero.es"
repository = "https://github.com/manuelcillero/pagetop"
license = "Apache-2.0 OR MIT"

[dependencies]
actix-web = "4.2.1"
pagetop = { path = "../pagetop", version = "0.0", features = ["mysql"], default-features = false }
# Modules.
pagetop-admin = { path = "../pagetop-admin", version = "0.0" }
pagetop-user = { path = "../pagetop-user", version = "0.0" }
pagetop-node = { path = "../pagetop-node", version = "0.0" }
# Themes.
pagetop-minimal = { path = "../pagetop-minimal", version = "0.0" }
pagetop-aliner = { path = "../pagetop-aliner", version = "0.0" }
pagetop-bootsier = { path = "../pagetop-bootsier", version = "0.0" }
pagetop-bulmix = { path = "../pagetop-bulmix", version = "0.0" }
