[package]
name = "drust"
version = "0.1.0"
edition = "2021"

authors = [
    "Manuel Cillero <manuel@cillero.es>"
]
description = """\
    A modern Content Management System for sharing the world.\
"""
homepage = "https://suitepro.cillero.es/projects/drust"
repository = "https://gitlab.com/manuelcillero/drust"

[dependencies]
actix-web = "3.3.3"
maud = { version = "0.23.0" }
serde = { version = "1.0", features = ["derive"] }

[dependencies.pagetop]
path = "../pagetop"
features = ["mysql"]
default-features = false
