[package]
name = "app"
version = "0.1.0"
edition = "2021"

# Ver más claves y sus definiciones en
# https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pagetop = { path = "pagetop" }
tokio = { version = "1.16", features = ["macros", "rt-multi-thread"] }

[[bin]]
name = "app"
