[package]
name = "module"
version = "0.1.0"
edition = "2021"

# Ver más claves y sus definiciones en
# https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Opcional. Para usar archivos y recursos binarios contenidos en la librería:
static-files = "0.2.3"
# Opcional. Para serializar estructuras de datos:
serde = { version = "1.0", features = ["derive"] }

# Si requiere acceso a base de datos:
pagetop = { version = "0.0", features = ["database"], default-features = false }
# pagetop = "0.0" (en otro caso)

[build-dependencies]
# Opcional. Para incluir archivos y recursos binarios en la propia librería:
pagetop-build = "0.0"
