[package]
name = "app"
version = "0.1.0"
edition = "2021"

# Ver más claves y sus definiciones en
# https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Si requiere acceso a base de datos (mysql, postgres y/o sqlite):
pagetop = { version = "0.0", features = ["mysql"], default-features = false }
# pagetop = "0.0" (en otro caso)

# Opcional. Para usar archivos y recursos binarios contenidos en el ejecutable:
static-files = "0.2.3"
# Opcional. Para serializar estructuras de datos:
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
# Opcional. Para incluir archivos y recursos binarios en el ejecutable:
pagetop-build = "0.0"
