[package]
name = "pagetop-admin"
version = "0.0.1"
edition = "2021"

authors = [
    "Manuel Cillero <manuel@cillero.es>"
]
description = """\
    Handles general site configuration for administrators.\
"""
homepage = "https://pagetop.cillero.es"
repository = "https://github.com/manuelcillero/pagetop"
license = "Apache-2.0 or MIT"

[dependencies]
pagetop = { path = "../pagetop", version = "0.0" }
maud = "0.24.0"
