[package]
name = "pagetop-aliner"
version = "0.0.9"
edition = "2021"

description = """\
    PageTop's default theme for schematic layouts, designed to be extended with subthemes.\
"""
categories  = ["web-programming", "gui"]
keywords    = ["pagetop", "theme", "css", "js"]

homepage    = { workspace = true }
repository  = { workspace = true }
authors     = { workspace = true }
license     = { workspace = true }

[dependencies]
pagetop.workspace = true

include_dir.workspace = true
static-files.workspace = true

tera = "1.20.0"

[build-dependencies]
pagetop-build.workspace = true
