[package]
name = "pagetop"
version = "0.0.28"
edition = "2021"

authors = [
    "Manuel Cillero <manuel@cillero.es>"
]
description = """\
    PageTop is an opinionated web development framework that uses the most stable and popular Rust \
    packages to build modular, extensible and configurable Server-side rendered solutions.\
"""
homepage = "https://pagetop.cillero.es"
repository = "https://github.com/manuelcillero/pagetop"
license = "Apache-2.0 OR MIT"

keywords = [
    "web", "cms", "framework", "frontend", "ssr"
]
categories = [
    "web-programming", "development-tools", "gui"
]

[dependencies]
async-trait   = "0.1.57"
concat-string = "1.0.1"
figlet-rs     = "0.1.4"
futures       = "0.3.24"
once_cell     = "1.15.0"
paste         = "1.0.9"
substring     = "1.4.5"
term_size     = "0.3.2"
url           = "2.3.1"

serde = "1.0"
nom = "7.1.1"
toml = "0.5.9"

tracing = "0.1.36"
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.15", features = ["json", "env-filter"] }
tracing-unwrap = { version = "0.9.2", default-features = false }
tracing-actix-web = "0.6.1"

fluent-templates = "0.8.0"
unic-langid = "0.9.0"

actix-web = "4.2.1"
actix-web-files = { package = "actix-files", version = "0.6.2" }
actix-web-static-files = "4.0.0"
static-files = "0.2.3"

maud = { version = "0.24.0", features = ["actix-web"] }

[dependencies.sea-orm]
version = "0.9.3"
features = ["debug-print", "macros", "runtime-async-std-native-tls"]
default-features = false
optional = true
[dependencies.sea-schema]
version = "0.9.4"
optional = true

[features]
default  = []
database = ["sea-orm", "sea-schema"]
mysql    = ["database", "sea-orm/sqlx-mysql"]
postgres = ["database", "sea-orm/sqlx-postgres"]
sqlite   = ["database", "sea-orm/sqlx-sqlite"]

[build-dependencies]
static-files = "0.2.3"

[dev-dependencies]
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }

[lib]
name = "pagetop"
