[package]
name = "pagetop"
version = "0.0.12"
edition = "2021"

authors = [
    "Manuel Cillero <manuel@cillero.es>"
]
description = """\
    PageTop is an opinionated framework for using the most stable and popular \
    Rust packages to build modular, extensible and configurable web solutions.\
"""
homepage = "https://suitepro.cillero.es/projects/pagetop"
repository = "https://gitlab.com/manuelcillero/pagetop"
license = "MIT"

keywords = [
    "web", "cms", "framework", "frontend", "ssr"
]
categories = [
    "web-programming", "development-tools", "gui"
]

[dependencies]
concat-string = "1.0.1"
doc-comment   = "0.3.3"
figlet-rs     = "0.1.3"
futures       = "0.3.21"
once_cell     = "1.10.0"
substring     = "1.4.5"
term_size     = "0.3.2"
url           = "2.2.2"

config_rs = { package = "config", version = "0.11.0", features = ["toml"] }

tracing = "0.1.34"
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.11", features = ["json", "env-filter"] }
tracing-unwrap = { version = "0.9.2", default-features = false }
tracing-actix-web = "0.2"

fluent-templates = "0.7.1"
unic-langid = "0.9.0"

actix-web = "3.3.3"
actix-web-static-files = "3.0.5"
actix-files = "0.4.1"

maud = { version = "0.23.0", features = ["actix-web"] }
sycamore = { version = "0.7.1", features = ["ssr"] }

serde = { version = "1.0", features = ["derive"] }

[dependencies.sea-orm]
version = "0.7.1"
features = ["debug-print", "macros", "runtime-async-std-native-tls"]
default-features = false
optional = true

[dependencies.sea-schema]
version = "0.7.1"
features = ["debug-print", "migration"]
default-features = false
optional = true

[features]
default  = []
mysql    = ["sea-orm", "sea-schema", "sea-orm/sqlx-mysql"]
postgres = ["sea-orm", "sea-schema", "sea-orm/sqlx-postgres"]
sqlite   = ["sea-orm", "sea-schema", "sea-orm/sqlx-sqlite"]

[build-dependencies]
actix-web-static-files = "3.0.5"

[dev-dependencies]
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }

[lib]
name = "pagetop"
