[package]
name = "pagetop"
version = "0.0.33"
edition = "2021"

authors = [
    "Manuel Cillero <manuel@cillero.es>"
]
description = """\
    PageTop is an opinionated web development framework that uses the most stable and popular Rust \
    packages to build modular, extensible and configurable Server-side rendered solutions.\
"""
homepage = "https://pagetop.cillero.es"
repository = "https://github.com/manuelcillero/pagetop"
license = "Apache-2.0 OR MIT"

keywords = [
    "web", "cms", "framework", "frontend", "ssr"
]
categories = [
    "web-programming", "development-tools", "gui"
]

[dependencies]
async-trait   = "0.1.63"
concat-string = "1.0.1"
doc-comment   = "0.3.3"
figlet-rs     = "0.1.4"
futures       = "0.3.25"
nom           = "7.1.3"
once_cell     = "1.17.0"
paste         = "1.0.11"
substring     = "1.4.5"
term_size     = "0.3.2"
toml          = "0.7.0"
url           = "2.3.1"

tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.16", features = ["json", "env-filter"] }
tracing-unwrap = { version = "0.10.0", default-features = false }
tracing-actix-web = "0.7.2"

fluent-templates = "0.8.0"
unic-langid = "0.9.1"

actix-web = "4.2.1"
actix-web-files = { package = "actix-files", version = "0.6.2" }
actix-web-static-files = "4.0.0"
static-files = "0.2.3"

pagetop-macros = { path = "../pagetop-macros", version = "0.0" }

maud = { version = "0.24.0", features = ["actix-web"] }

serde = { version = "1.0", features = ["derive"] }

[dependencies.sea-orm]
version = "0.10.7"
features = ["debug-print", "macros", "runtime-async-std-native-tls"]
default-features = false
optional = true
[dependencies.sea-schema]
version = "0.10.3"
optional = true

[features]
default  = []
database = ["sea-orm", "sea-schema"]
mysql    = ["database", "sea-orm/sqlx-mysql"]
postgres = ["database", "sea-orm/sqlx-postgres"]
sqlite   = ["database", "sea-orm/sqlx-sqlite"]

[build-dependencies]
pagetop-build = { path = "../pagetop-build", version = "0.0" }

[dev-dependencies]
tokio = { version = "1.24.2", features = ["macros", "rt-multi-thread"] }

[lib]
name = "pagetop"
