[package]
name = "pagetop"
version = "0.0.43"
edition = "2021"

authors = [
    "Manuel Cillero <manuel@cillero.es>"
]
description = """\
    PageTop is an opinionated web development framework that uses some of the most stable and \
    popular Rust packages to build modular, extensible and configurable Server-Side Rendering \
    (SSR) solutions.
"""
homepage = "https://pagetop.cillero.es"
repository = "https://github.com/manuelcillero/pagetop"
license = "Apache-2.0 OR MIT"

keywords = [
    "web", "cms", "framework", "frontend", "ssr"
]
categories = [
    "web-programming", "development-tools", "gui"
]

[lib]
name = "pagetop"

[features]
default  = []
database = ["futures", "sea-orm", "sea-schema"]
mysql    = ["database", "sea-orm/sqlx-mysql"]
postgres = ["database", "sea-orm/sqlx-postgres"]
sqlite   = ["database", "sea-orm/sqlx-sqlite"]

[dependencies]
async-trait   = "0.1.68"
concat-string = "1.0.1"
figlet-rs     = "0.1.5"
itoa          = "1.0.6"
nom           = "7.1.3"
once_cell     = "1.17.2"
paste         = "1.0.12"
substring     = "1.4.5"
term_size     = "0.3.2"
toml          = "0.7.4"
url           = "2.3.1"

tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.17", features = ["json", "env-filter"] }
tracing-unwrap = { version = "0.10.0", default-features = false }
tracing-actix-web = "0.7.5"

fluent-templates = "0.8.0"
unic-langid = { version = "0.9.1", features = ["macros"] }

actix-web = "4"
actix-session = { version = "0.7.2", features = ["cookie-session"] }

actix-web-files = { package = "actix-files", version = "0.6.2" }
actix-web-static-files = "4.0.1"
static-files = "0.2.3"

pagetop-macros = { version = "0.0", path = "../pagetop-macros" }

serde = { version = "1.0", features = ["derive"] }

[dependencies.futures]
version = "0.3.28"
optional = true

[dependencies.sea-orm]
version = "0.11.3"
features = ["debug-print", "macros", "runtime-async-std-native-tls"]
default-features = false
optional = true

[dependencies.sea-schema]
version = "0.11.0"
optional = true

[build-dependencies]
pagetop-build = { version = "0.0", path = "../pagetop-build" }

[package.metadata.docs.rs]
all-features = true
