[package]
name = "pagetop"
version = "0.0.1"
edition = "2021"

authors = [
    "Manuel Cillero <manuel@cillero.es>"
]
description = """\
    PageTop es un proyecto personal para aprender Rust. Incluye algunos de los \
    crates más estables y populares para desarrollar soluciones web modulares, \
    extensibles y configurables. También es un sistema para la gestión de \
    contenidos web.\
"""
homepage = "https://suitepro.cillero.es/projects/pagetop"
repository = "https://gitlab.com/manuelcillero/pagetop"
license = "MIT"

keywords = [
    "web", "cms", "framework", "frontend", "ssr"
]
categories = [
    "web-programming", "development-tools", "gui"
]

[dependencies]
doc-comment = "0.3.3"
downcast-rs = "1.2.0"
figlet-rs   = "0.1.3"
futures     = "0.3.21"
once_cell   = "1.10.0"
url         = "2.2.2"

config_rs = { package = "config", version = "0.11.0", features = ["toml"] }

tracing = "0.1.32"
tracing-appender = "0.2.1"
tracing-subscriber = { version = "0.3.9", features = ["json", "env-filter"] }
tracing-unwrap = { version = "0.9.2", default-features = false }
tracing-actix-web = "0.2"

fluent-templates = "0.6.1"
unic-langid = "0.9.0"

actix-web = "3.3.3"
actix-web-static-files = "3.0.5"

maud = { version = "0.23.0", features = ["actix-web"] }
sycamore = { version = "0.7.1", features = ["ssr"] }

serde = { version = "1.0", features = ["derive"] }

[dependencies.sea-orm]
version = "0.6.0"
features = ["debug-print", "macros", "runtime-async-std-native-tls"]
default-features = false
optional = true

[dependencies.sea-schema]
version = "0.6.0"
features = ["debug-print", "migration"]
default-features = false
optional = true

[dev-dependencies]
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }

[features]
default  = []
mysql    = ["sea-orm", "sea-schema", "sea-orm/sqlx-mysql"]
postgres = ["sea-orm", "sea-schema", "sea-orm/sqlx-postgres"]
sqlite   = ["sea-orm", "sea-schema", "sea-orm/sqlx-sqlite"]

[build-dependencies]
actix-web-static-files = "3.0.5"

[lib]
name = "pagetop"
