[package]
name = "app"
version = "0.1.0"
edition = "2021"

# Ver más claves y sus definiciones en
# https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pagetop = { path = "pagetop" }
actix-web = "3.3.3"
maud = { version = "0.23.0" }
serde = { version = "1.0", features = ["derive"] }
