[package]
name = "app"
version = "0.1.0"
edition = "2021"

# Ver más claves y sus definiciones en
# https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.pagetop]
path = "../pagetop"
# PageTop por defecto no requiere base de datos. Hay que habilitarla:
features = ["mysql"]
# features = ["postgres"]
# features = ["sqlite"]
# PageTop puede dar soporte a todas las bases de datos:
# features = ["mysql", "postgres", "sqlite"]
# En estos casos hay que deshabilitar las características predeterminadas:
default-features = false

[dependencies]
actix-web = "3.3.3"
# Opcional. Sólo si se usa la macro html!:
maud = { version = "0.23.0" }
# Opcional. Sólo si se usa base de datos:
sea-orm = { version = "0.6.0" }
# Opcional. Para la serialización de estructuras de datos:
serde = { version = "1.0", features = ["derive"] }
