[package]
name = "pagetop-build"
version = "0.3.2"

description = """
    Genera o prepara archivos estáticos para servirlos o incluirlos en un proyecto PageTop.
"""
categories = ["development-tools::build-utils"]
keywords = ["pagetop", "build", "assets", "resources", "static"]

repository.workspace = true
homepage.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
grass.workspace = true
minify-js.workspace = true
pagetop-statics.workspace = true
