[package]
name = "pagetop-bootsier"
version = "0.0.18"
edition = "2021"

description = """\
    PageTop theme that uses Bootstrap framework for versatile styles and components.\
"""
categories  = ["web-programming", "gui"]
keywords    = ["pagetop", "theme", "bootstrap", "css", "js"]

homepage    = { workspace = true }
repository  = { workspace = true }
authors     = { workspace = true }
license     = { workspace = true }

[dependencies]
pagetop = { workspace = true }
pagetop-aliner = { workspace = true }
static-files = { workspace = true }

[build-dependencies]
pagetop-build = { workspace = true }
