[package]
name = "pagetop-user"
version = "0.0.19"
edition = "2021"

description = "PageTop package for user, roles, permissions, and session management."
homepage = "https://pagetop.cillero.es"
repository = "https://github.com/manuelcillero/pagetop"
license = "MIT OR Apache-2.0"

authors = [
    "Manuel Cillero <manuel@cillero.es>"
]
categories = [
    "web-programming", "gui", "authentication"
]
keywords = [
    "pagetop", "user", "login", "grants", "preferences"
]

[dependencies]
pagetop = { version = "0.0", path = "../../", features = ["database"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
