[package]
name = "pagetop-user"
version = "0.0.15"
edition = "2021"

authors = [
    "Manuel Cillero <manuel@cillero.es>"
]
description = """\
    Facilitates user management, including roles, permissions, and session handling, for \
    applications built on PageTop.\
"""
homepage = "https://pagetop.cillero.es"
repository = "https://github.com/manuelcillero/pagetop"
license = "MIT OR Apache-2.0"

[dependencies]
pagetop = { version = "0.0", path = "../../", features = ["database"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
