[app]
name = "Drust"
description = """\
    A modern Content Management System for sharing the world.\
"""
language = "es-ES"
#theme = "Aliner"
#theme = "Minimal"
theme = "Bootsier"

[database]
db_type = "mysql"
db_name = "drust"
db_user = "drust"
db_pass = "DrU__#3T"

[log]
tracing = "Info,sqlx::query=Warn"
