[package]
name = "pagetop-bulmix"
version = "0.0.16"
edition = "2021"

authors = [
    "Manuel Cillero <manuel@cillero.es>"
]
description = """\
    PageTop theme that utilizes the Bulma framework for sleek, responsive design elements.\
"""
homepage = "https://pagetop.cillero.es"
repository = "https://github.com/manuelcillero/pagetop"
license = "MIT OR Apache-2.0"

[dependencies]
pagetop = { version = "0.0", path = "../../" }
static-files = "0.2.3"

[build-dependencies]
pagetop-build = { version = "0.0", path = "../../helpers/pagetop-build" }
