[package]
name = "pagetop-bulmix"
version = "0.0.16"
edition = "2021"

description = "PageTop theme that uses the Bulma framework for sleek, responsive design elements."
homepage = "https://pagetop.cillero.es"
repository = "https://github.com/manuelcillero/pagetop"
license = "MIT OR Apache-2.0"

authors = [
    "Manuel Cillero <manuel@cillero.es>"
]
categories = [
    "web-programming", "gui"
]
keywords = [
    "pagetop", "theme", "bulma", "css", "js"
]

[dependencies]
pagetop = { version = "0.0", path = "../../" }
static-files = "0.2.3"

[build-dependencies]
pagetop-build = { version = "0.0", path = "../../helpers/pagetop-build" }
