[package]
name = "pagetop-user"
version = "0.0.1"
edition = "2021"

authors = [
    "Manuel Cillero <manuel@cillero.es>"
]
description = """\
    Allows content to be submitted to the site and displayed on pages.\
"""
homepage = "https://suitepro.cillero.es/projects/pagetop"
repository = "https://gitlab.com/manuelcillero/pagetop"

[dependencies]
pagetop = { path = "../pagetop" }
sea-orm = { version = "0.7.1" }
serde = { version = "1.0", features = ["derive"] }
