[app]
#theme = "Basic"
#theme = "Chassis"
theme = "Inception"
#theme = "Bootsier"
#theme = "Bulmix"
language = "es-ES"

[log]
tracing = "Info,pagetop=Debug,sqlx::query=Warn"

[dev]
#static_files = "../pagetop/static"
