[app]
name = "PageTop Application"
description = "Developed with the amazing PageTop framework."
# Tema predeterminado.
theme = "Bootsier"
# Idioma (localización) predeterminado.
language = "en-US"
# Dirección predeterminada para el texto: "ltr", "rtl" o "auto".
direction = "ltr"
# Rótulo al inicio: "Off", "Slant", "Small", "Speed" o "Starwars".
startup_banner = "Slant"

[database]
# Conecta con una base de datos (opcional).
# Tipo de base de datos (mysql, postgres ó sqlite).
db_type = ""
# Nombre (para mysql/postgres) o referencia (para sqlite) de la base de datos.
db_name = ""
# Usuario y contraseña (para mysql/postgres).
db_user = ""
db_pass = ""
# Servidor (para mysql/postgres).
db_host = "localhost"
# Puerto (para mysql/postgres), siendo 0 el puerto predeterminado (3306 ó 5432).
db_port = 0
# Número máximo de conexiones habilitadas.
max_pool_size = 5

[dev]
# Los archivos estáticos requeridos por temas y componentes incluidos en PageTop
# se integran de manera predeterminada en el binario ejecutable. Sin embargo, es
# útil servir estos archivos desde su propio directorio durante el desarrollo ya
# que no requiere compilar cada vez que se modifican. En este caso, normalmente,
# basta con indicar el directorio "pagetop/static".
static_files = ""

[log]
# Traza de ejecución: "Error", "Warn", "Info", "Debug" o "Trace".
# Ejemplos: "Error,actix_server::builder=Info,tracing_actix_web=Debug".
tracing = "Info"
# En terminal ("Stdout") o archivos "Daily", "Hourly", "Minutely" o "Endless".
rolling = "Stdout"
# Directorio para los archivos de traza (si rolling != "Stdout").
path = "log"
# Prefijo para los archivos de traza (si rolling != "Stdout").
prefix = "tracing.log"
# Presentación de las trazas: "Full", "Compact", "Pretty" o "Json".
format = "Full"

[server]
# Configuración del servidor web.
bind_address = "localhost"
bind_port = 8088
