[app]
name = "PageTop Application"
description = "Developed with the amazing PageTop framework."
# Tema predeterminado.
theme = "Bootsier"
# Idioma (localización) predeterminado.
language = "en-US"
# Dirección predeterminada para el texto: "ltr", "rtl" o "auto".
direction = "ltr"
# Rótulo al inicio: "Off", "Slant", "Small", "Speed" o "Starwars".
startup_banner = "Small"

[log]
# Traza de ejecución: "Error", "Warn", "Info", "Debug" o "Trace".
# Ejemplos: "Error,actix_server::builder=Info,tracing_actix_web=Debug".
tracing = "Info"
# En terminal ("Stdout") o archivos "Daily", "Hourly", "Minutely" o "Endless".
rolling = "Daily"
# Directorio para los archivos de traza (si rolling != "Stdout").
path = "log"
# Prefijo para los archivos de traza (si rolling != "Stdout").
prefix = "tracing.log"
# Presentación de las trazas: "Json", "Full", "Compact" o "Pretty".
format = "Json"

[database]
# Ajustes para conectar con la base de datos.
# El tipo de base de datos es una característica de compilación.
# Nombre (mysql/postgres) o referencia (sqlite) de la base de datos.
db_name = "dbname"
# Usuario y contraseña (mysql/postgres).
db_user = "dbuser"
db_pass = "dbpass"
# Servidor (mysql/postgres) y puerto predeterminado (0 para 3306 ó 5432).
db_host = "localhost"
db_port = 0
# Número máximo de conexiones habilitadas.
max_pool_size = 5

[webserver]
# Configuración del servidor web.
bind_address = "localhost"
bind_port = 8088
