[package]
name = "pagetop-node"
version = "0.0.20"
edition = "2021"

description = "PageTop package for easy content type creation and customization."
homepage = "https://pagetop.cillero.es"
repository = "https://github.com/manuelcillero/pagetop"
license = "MIT OR Apache-2.0"

authors = [
    "Manuel Cillero <manuel@cillero.es>"
]
categories = [
    "web-programming", "gui"
]
keywords = [
    "pagetop", "node", "cms", "content", "workflow"
]

[dependencies]
pagetop = { version = "0.0", path = "../../", features = ["database"], default-features = false }
