[package]
name = "pagetop-node"
version = "0.0.19"
edition = "2021"

authors = [
    "Manuel Cillero <manuel@cillero.es>"
]
description = """\
    PageTop package that enables the creation and customization of content types, enhancing \
    website content management.\
"""
homepage = "https://pagetop.cillero.es"
repository = "https://github.com/manuelcillero/pagetop"
license = "MIT OR Apache-2.0"

[dependencies]
pagetop = { version = "0.0", path = "../../", features = ["database"], default-features = false }
