[package]
name = "pagetop-hljs"
version = "0.0.14"
edition = "2021"

description = """\
    Integra HighlightJS para mostrar fragmentos de código con resaltado de sintaxis con PageTop.\
"""
categories = ["web-programming", "gui"]
keywords = ["pagetop", "highlight", "parse", "parsing", "component"]

repository.workspace = true
homepage.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
pagetop.workspace = true

serde.workspace = true
static-files.workspace = true

[build-dependencies]
pagetop-build.workspace = true
